# Generated by Django 3.1.4 on 2020-12-20 12:24

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='word',
            field=models.CharField(default=catalog.models.word_default, max_length=25, verbose_name='WORD'),
        ),
    ]
