# Generated by Django 3.1.4 on 2020-12-20 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201220_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(help_text='Long description of project', max_length=400)),
                ('brief_description', models.CharField(help_text='Brief description of project for list view', max_length=150)),
                ('languages', models.CharField(help_text='Enter programming languages used.', max_length=150)),
                ('github_repo', models.CharField(help_text='Link to github repo for project.', max_length=200)),
                ('primary_image_link', models.CharField(help_text='Enter path for primary image to be used. Use images/project_media', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_image', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('y', 'Use'), ('n', "Don't Use")], default='n', help_text='Use image y/n?', max_length=1)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.project')),
            ],
        ),
    ]
