# Generated by Django 3.1.4 on 2020-12-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201221_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='link_to_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
