# Generated by Django 3.1.4 on 2020-12-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20201221_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='link_to_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
